import Link from "next/link";

import { PostRowActions } from "@/components/admin/post-row-actions";
import { getAdminCategories } from "@/lib/api/categories";
import { getAdminPosts } from "@/lib/api/posts";
import { deletePostAction, publishPostAction, unpublishPostAction } from "./actions";

export default async function AdminBlogPage({ searchParams }: { searchParams: Promise<{ search?: string; status?: "draft" | "published"; category?: string; page?: string }> }) {
  const params = await searchParams;
  const page = Math.max(Number(params.page) || 1, 1);
  const [posts, categories] = await Promise.all([getAdminPosts({ search: params.search, status: params.status, categorySlug: params.category, page }), getAdminCategories()]);
  const query = new URLSearchParams(); if (params.search) query.set("search", params.search); if (params.status) query.set("status", params.status); if (params.category) query.set("category", params.category);
  return <section><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm uppercase tracking-[0.2em] text-black/50">CMS</p><h1 className="mt-2 text-4xl font-semibold">Blog</h1></div><Link className="bg-black px-4 py-2 text-sm font-medium text-white" href="/admin/blog/new">New post</Link></div><form className="mb-6 grid gap-3 md:grid-cols-[1fr_180px_220px_auto]"><input className="border border-black/20 px-3 py-2" defaultValue={params.search} name="search" placeholder="Search titles" /><select className="border border-black/20 px-3 py-2" defaultValue={params.status ?? ""} name="status"><option value="">All statuses</option><option value="draft">Draft</option><option value="published">Published</option></select><select className="border border-black/20 px-3 py-2" defaultValue={params.category ?? ""} name="category"><option value="">All categories</option>{categories.map((category) => <option key={category.id} value={category.slug}>{category.name}</option>)}</select><button className="border border-black/20 px-4 py-2" type="submit">Filter</button></form>{posts.length === 0 ? <div className="border border-dashed border-black/20 px-6 py-12 text-black/60">No posts match these filters.</div> : <div className="overflow-x-auto border border-black/10 bg-white"><table className="w-full min-w-[950px] text-left text-sm"><thead className="border-b border-black/10 bg-zinc-50 text-xs uppercase text-black/50"><tr><th className="px-4 py-3">Title</th><th className="px-4 py-3">Category</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Published</th><th className="px-4 py-3">Created</th><th className="px-4 py-3">Updated</th><th className="px-4 py-3"><span className="sr-only">Actions</span></th></tr></thead><tbody className="divide-y divide-black/10">{posts.map((post) => <tr key={post.id}><td className="px-4 py-4 font-medium">{post.title}</td><td className="px-4 py-4 text-black/60">{post.category?.name ?? "-"}</td><td className="px-4 py-4">{post.status}</td><td className="px-4 py-4 text-black/60">{post.publishedAt?.toLocaleDateString() ?? "-"}</td><td className="px-4 py-4 text-black/60">{post.createdAt.toLocaleDateString()}</td><td className="px-4 py-4 text-black/60">{post.updatedAt.toLocaleDateString()}</td><td className="px-4 py-4"><PostRowActions deleteAction={deletePostAction} editHref={`/admin/blog/${post.id}/edit`} id={post.id} isPublished={post.isPublished} publishAction={publishPostAction} unpublishAction={unpublishPostAction} /></td></tr>)}</tbody></table></div>}<div className="mt-6 flex gap-3 text-sm">{page > 1 ? <Link className="border border-black/20 px-3 py-2" href={`/admin/blog?${query.toString()}&page=${page - 1}`}>Previous</Link> : null}{posts.length === 20 ? <Link className="border border-black/20 px-3 py-2" href={`/admin/blog?${query.toString()}&page=${page + 1}`}>Next</Link> : null}</div></section>;
}