"use client";

import { useActionState } from "react";

import { MediaPicker } from "@/components/admin/media-picker";
import { SeoPreview } from "@/components/admin/seo-preview";
import { saveGlobalSeoAction, type GlobalSeoActionState } from "@/app/admin/(protected)/seo/actions";

export function GlobalSeoForm({ seo, media }: { seo?: { siteTitle: string | null; siteDescription: string | null; siteUrl: string | null; twitterCard: string | null; defaultRobots: string | null; defaultOgImageMediaId: number | null; ogImage?: { url: string; alt: string } | null }; media: { id: number; filename: string; url: string; width: number; height: number; alt: string }[] }) {
  const [state, formAction, pending] = useActionState(saveGlobalSeoAction, {} as GlobalSeoActionState);
  return <form action={formAction} className="mt-10 space-y-6"><label className="block text-sm font-medium">Site title<input className="mt-2 w-full border border-black/20 px-3 py-2 font-normal" defaultValue={seo?.siteTitle ?? "Personal website"} maxLength={120} name="siteTitle" required /></label><label className="block text-sm font-medium">Site description<textarea className="mt-2 min-h-24 w-full border border-black/20 px-3 py-2 font-normal" defaultValue={seo?.siteDescription ?? ""} maxLength={320} name="siteDescription" /></label><label className="block text-sm font-medium">Site URL<input className="mt-2 w-full border border-black/20 px-3 py-2 font-normal" defaultValue={seo?.siteUrl ?? "http://localhost:3000"} name="siteUrl" required type="url" /></label><MediaPicker media={media} name="defaultOgImageMediaId" selectedId={seo?.defaultOgImageMediaId} /><div className="grid gap-5 md:grid-cols-2"><label className="block text-sm font-medium">Twitter card<select className="mt-2 w-full border border-black/20 px-3 py-2 font-normal" defaultValue={seo?.twitterCard ?? "summary_large_image"} name="twitterCard"><option value="summary_large_image">Summary large image</option><option value="summary">Summary</option></select></label><label className="block text-sm font-medium">Robots<select className="mt-2 w-full border border-black/20 px-3 py-2 font-normal" defaultValue={seo?.defaultRobots ?? "index,follow"} name="defaultRobots"><option value="index,follow">Index, follow</option><option value="noindex,nofollow">No index, no follow</option></select></label></div><SeoPreview description={seo?.siteDescription ?? ""} image={seo?.ogImage?.url} title={seo?.siteTitle ?? "Personal website"} url={seo?.siteUrl ?? "http://localhost:3000"} />{state.error ? <p className="text-sm text-red-700">{state.error}</p> : null}<button className="bg-black px-5 py-3 font-medium text-white disabled:opacity-50" disabled={pending} type="submit">{pending ? "Saving..." : "Save global SEO"}</button></form>;
}