"use client";

import { useActionState } from "react";
import { MediaPicker } from "@/components/admin/media-picker";
import { SeoFields } from "@/components/admin/seo-fields";
import type { PostActionState } from "@/app/admin/(protected)/blog/actions";

type Option = { id: number; name: string };
type MediaOption = { id: number; filename: string; url: string; width: number; height: number; alt: string };
type SeoOption = { metaTitle: string | null; metaDescription: string | null; canonicalUrl: string | null; ogTitle: string | null; ogDescription: string | null; defaultOgImageMediaId: number | null; robotsIndex: boolean; robotsFollow: boolean };
type PostFormProps = { action: (state: PostActionState, formData: FormData) => Promise<PostActionState>; submitLabel: string; categories: Option[]; tags: Option[]; media: MediaOption[]; seo?: SeoOption; post?: { id: number; title: string; slug: string; excerpt: string; content: string; coverImageUrl: string | null; mediaId: number | null; category: { id: number } | null; tags: { id: number }[]; status: string; publishedAt: Date | null } };

export function PostForm({ action, submitLabel, categories, tags, media, seo, post }: PostFormProps) {
  const [state, formAction, pending] = useActionState(action, {});
  const publishedAt = post?.publishedAt ? new Date(post.publishedAt).toISOString().slice(0, 16) : "";
  const selectedTags = new Set(post?.tags.map((tag) => tag.id));
  return <form action={formAction} className="space-y-6">{post ? <input name="id" type="hidden" value={post.id} /> : null}<MediaPicker media={media} selectedId={post?.mediaId} /><label className="block text-sm font-medium">Title<input className="mt-2 w-full border border-black/20 px-3 py-2 font-normal" defaultValue={post?.title} name="title" required /></label><label className="block text-sm font-medium">Slug<input className="mt-2 w-full border border-black/20 px-3 py-2 font-normal" defaultValue={post?.slug} name="slug" required /></label><label className="block text-sm font-medium">Excerpt<textarea className="mt-2 min-h-24 w-full border border-black/20 px-3 py-2 font-normal" defaultValue={post?.excerpt} name="excerpt" required /></label><label className="block text-sm font-medium">Markdown content<textarea className="mt-2 min-h-[28rem] w-full border border-black/20 px-3 py-2 font-mono text-sm font-normal" defaultValue={post?.content} name="content" required /></label><div className="grid gap-6 md:grid-cols-2"><label className="block text-sm font-medium">Cover image URL<input className="mt-2 w-full border border-black/20 px-3 py-2 font-normal" defaultValue={post?.coverImageUrl ?? ""} name="coverImageUrl" type="url" /></label><label className="block text-sm font-medium">Category<select className="mt-2 w-full border border-black/20 px-3 py-2 font-normal" defaultValue={post?.category?.id ?? ""} name="categoryId" required><option disabled value="">Select a category</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className="block text-sm font-medium">Published at<input className="mt-2 w-full border border-black/20 px-3 py-2 font-normal" defaultValue={publishedAt} name="publishedAt" type="datetime-local" /></label><label className="block text-sm font-medium">Status<select className="mt-2 w-full border border-black/20 px-3 py-2 font-normal" defaultValue={post?.status ?? "draft"} name="status"><option value="draft">Draft</option><option value="published">Published</option></select></label></div><fieldset><legend className="mb-2 text-sm font-medium">Tags</legend><div className="flex flex-wrap gap-4">{tags.map((tag) => <label className="flex items-center gap-2 text-sm" key={tag.id}><input defaultChecked={selectedTags.has(tag.id)} name="tagIds" type="checkbox" value={tag.id} />{tag.name}</label>)}</div></fieldset><SeoFields media={media} seo={seo} />{state.error ? <p className="text-sm text-red-700">{state.error}</p> : null}<button className="bg-black px-5 py-3 font-medium text-white disabled:opacity-50" disabled={pending} type="submit">{pending ? "Saving..." : submitLabel}</button></form>;
}