"use client";

import { useActionState } from "react";
import { MediaPicker } from "@/components/admin/media-picker";
import { SeoFields } from "@/components/admin/seo-fields";
import type { ProjectActionState } from "@/app/admin/(protected)/projects/actions";

type MediaOption = { id: number; filename: string; url: string; width: number; height: number; alt: string };
type SeoOption = { metaTitle: string | null; metaDescription: string | null; canonicalUrl: string | null; ogTitle: string | null; ogDescription: string | null; defaultOgImageMediaId: number | null; robotsIndex: boolean; robotsFollow: boolean };
type ProjectFormProps = { action: (state: ProjectActionState, formData: FormData) => Promise<ProjectActionState>; submitLabel: string; media: MediaOption[]; seo?: SeoOption; project?: { id: number; title: string; slug: string; summary: string; content: string; imageUrl: string | null; repositoryUrl: string | null; projectUrl: string | null; technologies: string[]; isFeatured: boolean; isPublished: boolean; publishedAt: Date | null; mediaId: number | null } };

export function ProjectForm({ action, submitLabel, media, seo, project }: ProjectFormProps) {
  const [state, formAction, pending] = useActionState(action, {});
  const publishedAt = project?.publishedAt ? new Date(project.publishedAt).toISOString().slice(0, 16) : "";
  return <form action={formAction} className="space-y-6">{project ? <input name="id" type="hidden" value={project.id} /> : null}<MediaPicker media={media} selectedId={project?.mediaId} /><label className="block text-sm font-medium">Title<input className="mt-2 w-full border border-black/20 px-3 py-2 font-normal" defaultValue={project?.title} name="title" required /></label><label className="block text-sm font-medium">Slug<input className="mt-2 w-full border border-black/20 px-3 py-2 font-normal" defaultValue={project?.slug} name="slug" required /></label><label className="block text-sm font-medium">Description<textarea className="mt-2 min-h-24 w-full border border-black/20 px-3 py-2 font-normal" defaultValue={project?.summary} name="summary" required /></label><label className="block text-sm font-medium">Content<textarea className="mt-2 min-h-64 w-full border border-black/20 px-3 py-2 font-normal" defaultValue={project?.content} name="content" required /></label><div className="grid gap-6 md:grid-cols-2"><label className="block text-sm font-medium">Cover image URL<input className="mt-2 w-full border border-black/20 px-3 py-2 font-normal" defaultValue={project?.imageUrl ?? ""} name="imageUrl" type="url" /></label><label className="block text-sm font-medium">Technologies<input className="mt-2 w-full border border-black/20 px-3 py-2 font-normal" defaultValue={project?.technologies.join(", ")} name="technologies" /></label><label className="block text-sm font-medium">GitHub URL<input className="mt-2 w-full border border-black/20 px-3 py-2 font-normal" defaultValue={project?.repositoryUrl ?? ""} name="repositoryUrl" type="url" /></label><label className="block text-sm font-medium">Demo URL<input className="mt-2 w-full border border-black/20 px-3 py-2 font-normal" defaultValue={project?.projectUrl ?? ""} name="projectUrl" type="url" /></label><label className="block text-sm font-medium">Published at<input className="mt-2 w-full border border-black/20 px-3 py-2 font-normal" defaultValue={publishedAt} name="publishedAt" type="datetime-local" /></label></div><div className="flex gap-6"><label className="flex items-center gap-2 text-sm"><input defaultChecked={project?.isFeatured} name="isFeatured" type="checkbox" />Featured</label><label className="flex items-center gap-2 text-sm"><input defaultChecked={project?.isPublished} name="isPublished" type="checkbox" />Published</label></div><SeoFields media={media} seo={seo} />{state.error ? <p className="text-sm text-red-700">{state.error}</p> : null}<button className="bg-black px-5 py-3 font-medium text-white disabled:opacity-50" disabled={pending} type="submit">{pending ? "Saving..." : submitLabel}</button></form>;
}